# disable sudo to use container based build
sudo: false

# Enabling test on Linux and OS X
os:
  - linux
  - osx

osx_image: xcode9.3

# Use Build Matrix to do lint and build seperately
env:
  matrix:
    - TASK=lint LINT_LANG=cpp
    - TASK=lint LINT_LANG=python
    - TASK=doc
    - TASK=build
    - TASK=test

matrix:
  exclude:
    - os: osx
      env: TASK=lint LINT_LANG=cpp
    - os: osx
      env: TASK=lint LINT_LANG=python
    - os: osx
      env: TASK=doc

# dependent apt packages
dist: xenial
addons:
  apt:
    packages:
      - doxygen
      - libopenmpi-dev
      - wget
      - git
      - libcurl4-openssl-dev
      - unzip
      - python-numpy
      - gcc-4.8
      - g++-4.8
  homebrew:
    packages:
      - gcc48
      - graphviz
    update: true
      
before_install:
  - git clone https://github.com/chenqin/dmlc-core
  - export TRAVIS=dmlc-core/scripts/travis/
  - source ${TRAVIS}/travis_setup_env.sh

install:
  - pip install --user cpplint pylint kubernetes urllib3

script: scripts/travis_script.sh


before_cache:
  - ${TRAVIS}/travis_before_cache.sh


cache:
  directories:
    - ${HOME}/.cache/usr


notifications:
# Emails are sent to the committer's git-configured email address by default,
  email:
    on_success: change
    on_failure: always


