# disable sudo to use container based build
sudo: false

# Use Build Matrix to do lint and build seperately
env:
  matrix:
    - TASK=lint LINT_LANG=cpp
    - TASK=lint LINT_LANG=python
    - TASK=doc
    - TASK=build
    - TASK=mpi-build
    - TASK=cmake-build
    - TASK=test CXX=g++-4.8

# dependent apt packages
dist: xenial
addons:
  apt:
    packages:
      - doxygen
      - libopenmpi-dev
      - wget
      - git
      - libcurl4-openssl-dev
      - unzip
      - python-numpy
      - gcc-4.8
      - g++-4.8
      - openmpi-bin
      - openmpi-common
      - openssh-client
      - openssh-server
      - libopenmpi-dev
      
before_install:
  - export TRAVIS=dmlc-core/scripts/travis/
  - source ${TRAVIS}/travis_setup_env.sh

install:
  - pip install --user cpplint pylint kubernetes urllib3

script: scripts/travis_script.sh


before_cache:
  - ${TRAVIS}/travis_before_cache.sh


cache:
  directories:
    - ${HOME}/.cache/usr


notifications:
# Emails are sent to the committer's git-configured email address by default,
  email:
    on_success: change
    on_failure: always


